<style>
    #description,#descriptionUa {
        width: 98%;
        height: 100px;
        resize: none;
    }
    #title,#titleUa,#icon,#category{
        width: 98%;
    }
</style>
<?php
$this->layout()->ckeditor = true;
?>
<?php
if ($this->lang == "ua") $this->title = "Додати статтю"; else
$this->title = "Добавить статью "; ?>
<div class="settings">
<?php
echo $this->errMessage;
echo $this->form;
?>
<?php echo $this->CKEditor( 'body' );
      echo $this->CKEditor( 'bodyUa' );?>
</div>
