<h2>Аналитика</h2>

<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ua/stat/?id=25746824&amp;from=informer"
   target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/25746824/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                                       style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: дані за сьогодні  (перегляди, візити та унікальні відвідувачі)" onclick="try{Ya.Metrika.informer({i:this,id:25746824,lang:'ua'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->