<?php
if ($this->lang == "ua"){
    $this->title = "Видалення підкатегорії";
    $this->headTitle($this->title);
    ?>
    <p>Ви дійсно хочете видалити підкатегорію
        '<?php echo $this->escape($this->category['nameUa']); ?>'?
    </p>
    <form action="<?php echo $this->url(array('action' => 'deletesubcat')); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->category['id']; ?>"/>
            <input type="submit" name="del" value="Так"/>
            <input type="submit" name="del" value="Ні"/>
        </div>
    </form>
<?php } else { $this->title = "Удаление подкатегории";
    $this->headTitle($this->title);
    ?>
    <p>Вы действительно хотите удалить подкатегорию
        '<?php echo $this->escape($this->category['name']); ?>'?
    </p>
    <form action="<?php echo $this->url(array('action' => 'deletesubcat')); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->category['id']; ?>"/>
            <input type="submit" name="del" value="Да"/>
            <input type="submit" name="del" value="Нет"/>
        </div>
    </form>
<?php } ?>