<?php
$this->title = "Удаление записи";
$this->headTitle($this->title);
?>
<p>Вы действительно хотите удалить фильм
    '<?php echo $this->escape($this->post['title']); ?>' от
    '<?php echo $this->escape($this->post['director']); ?>'?
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->post['id']; ?>"/>
        <input type="submit" name="del" value="Да"/>
        <input type="submit" name="del" value="Нет"/>
    </div>
</form>
