<?php
if ($this->lang == "ua"){
    $this->title = "Видалення розділу";
    $this->headTitle($this->title);
?>
<p>Ви дійсно хочете видалити розділ
    '<?php echo $this->escape($this->part['nameUa']); ?>'?
</p>
<form action="<?php echo $this->url(array('action' => 'deletepart')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->part['id']; ?>"/>
        <input type="submit" name="del" value="Так"/>
        <input type="submit" name="del" value="Ні"/>
    </div>
</form>
<?php } else {    $this->title = "Удаление раздела";
    $this->headTitle($this->title);
    ?>
    <p>Вы действительно хотите удалить раздел
        '<?php echo $this->escape($this->part['name']); ?>'?
    </p>
    <form action="<?php echo $this->url(array('action' => 'deletepart')); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->part['id']; ?>"/>
            <input type="submit" name="del" value="Да"/>
            <input type="submit" name="del" value="Нет"/>
        </div>
    </form>
<?php }?>
