<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Блог";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'add')); ?>">Добавить статью</a></p>
<table>
    <tr>
        <th>Название</th>
        <th>Категория</th>
        <th>текст</th>
        <th>Автор</th>
        <th>Дата</th>
        <th></th>
        <th></th>
    </tr>
    <?php
    // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
    echo $this->partialLoop('/partials/posts.phtml', $this->posts);
    ?>
</table>
