<?php if(!isset($_COOKIE['lang'])) $_COOKIE['lang'] = "ru";?>
<?php  if (Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->role == 'admin')  {?>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'add')); ?>" class="btn btn-success">
        <?php if($this->lang == "ua") echo 'Додати статтю'; else echo 'Добавить статью';?></a></p>
<?php } ?>

    <?php
    // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
    if($this->lang == "ua")
        echo $this->partialLoop('/partials/postsUa.phtml', $this->paginator);
    else
        echo $this->partialLoop('/partials/posts.phtml', $this->paginator);
    ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator_control.phtml'); ?>
