
<?php
if ($this->lang == "ua") $this->title = "Додати питання"; else
$this->title = "Добавить вопрос"; ?>
<div class="settings">
    <ul class="breadcrumb">
        <li><a href="/test/construct/"><?php if($this->lang == "ua") echo 'Конструктор тестів'; else echo 'Конструктор тестов';?></a>
            <span class="divider">/</span></li>
        <li><a href="/test/typequestion/"><?php if($this->lang == "ua") echo 'Вибрати складність питання'; else echo 'Выбрать сложность вопроса';?></a>
            <span class="divider">/</span></li>
        <li class="active"><?php if($this->lang == "ua") echo 'Додати питання'; else echo 'Добавить вопрос';?></li>
    </ul>
<?php
echo $this->errMessage;
echo $this->form;
?>
</div>