<link href="/css/jquery.autocomplete.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-1.5.2.min.js"></script>
<script type="text/javascript" src="/js/jquery.autocomplete.pack.js"></script>
<script type="text/javascript" src="/js/script.js"></script>
<?php
if ($this->lang == "ua") $this->title = "Додати питання"; else
$this->title = "Добавить вопрос";
echo $this->errMessage;
echo $this->form;
?>

