<?php
// Создаём заголовок страницы, который загрузится в layout
if ($this->lang == "ua") $this->title = "Конструктор тестів"; else
    $this->title = "Конструктор тестов";
$this->headTitle($this->title);
?>
<div class="settings">
    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'addtest')); ?>" class="btn btn-small btn-success">
        <i class="icon-plus icon-white"></i>
        <?php if ($this->lang == "ua") echo 'Тест'; else echo 'Тест'; ?></a>

    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'typequestion')); ?>" class="btn btn-small  btn-success">
        <i class="icon-plus icon-white"></i>
        <?php if ($this->lang == "ua") echo 'Питання'; else echo 'Вопрос'; ?></a>

    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'uploadtest')); ?>" class="btn btn-small btn-success" >
        <i class="icon-arrow-down icon-white"></i>
        <?php if ($this->lang == "ua") echo 'Завантажити питання'; else echo 'Загрузить вопросы'; ?></a>

    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'addtopic')); ?>" class="btn btn-small  btn-success"
       > <i class="icon-plus icon-white"></i>
        <?php if ($this->lang == "ua") echo 'Тему'; else echo 'Тему'; ?> </a>

    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'random')); ?>" class="btn btn-small  btn-success" >
        <i class=" icon-check icon-white"></i>
        <?php if ($this->lang == "ua") echo 'Випадковий тест'; else echo 'Случайный тест'; ?></a>

    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'pattern')); ?>" class="btn btn-small btn-success" >
        <i class=" icon-list icon-white"></i>
        <?php if ($this->lang == "ua") echo 'Створити шаблон'; else echo 'Создать шаблон'; ?></a>
    <hr>



    <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'allpattern')); ?>">
    <?php if ($this->lang == "ua") echo 'Управління шаблонами'; else echo 'Управление шаблонами'; ?></a>

    <h4><?php if ($this->lang == "ua") echo 'Теми'; else echo 'Темы'; ?>:</h4>
    <table class="table table-condensed">
        <?php
        // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
        echo $this->partialLoop('/partials/topic.phtml', $this->topic);
        ?>
    </table>
    <hr>
    <div class="row-fluid">
        <div class="span6">
            <h4><?php if ($this->lang == "ua") echo 'Тести'; else echo 'Тесты'; ?>:</h4>
            <table class="table table-condensed">
                <?php
                // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
                echo $this->partialLoop('/partials/tests.phtml', $this->tests);
                ?>
            </table>
        </div>
        <div class="span6">
            <h4><?php if ($this->lang == "ua") echo 'Питання'; else echo 'Вопросы'; ?>:</h4>
            <table class="table table-condensed">
                <?php
                if ($this->lang == "ua") echo $this->partialLoop('/partials/questionUa.phtml', $this->question); else
                    echo $this->partialLoop('/partials/question.phtml', $this->question);
                ?>
            </table>
            <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'allquestion')); ?>">
                <?php if ($this->lang == "ua") echo 'Дивитися все ...'; else echo 'Смотреть все...'; ?></a>
        </div>
    </div>
</div>