<?php
if($this->lang == "ua") {
    $this->title = "Видалення шаблону";
    $this->headTitle($this->title);
    ?>
    <p>Ви дійсно хочете видалити шаблон
        '<?php echo $this->escape($this->pattern['name']); ?>'
    </p>
    <form action="<?php echo $this->url(array('action' => 'deletepattern')); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->pattern['id']; ?>"/>
            <input type="submit" name="del" value="Так"/>
            <input type="submit" name="del" value="Ні"/>
        </div>
    </form>
<?php } else {

    $this->title = "Удаление шаблона";
    $this->headTitle($this->title);
    ?>
    <p>Вы действительно хотите удалить шаблон
        '<?php echo $this->escape($this->pattern['name']); ?>'
    </p>
    <form action="<?php echo $this->url(array('action' => 'deletepattern')); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->pattern['id']; ?>"/>
            <input type="submit" name="del" value="Да"/>
            <input type="submit" name="del" value="Нет"/>
        </div>
    </form>
<?php }?>