<script type="text/javascript">
    $(document).ready(function(){
        var h1 = document.getElementById('topicId');
        var h4 = document.getElementById('testId');
        $("#tests0").addClass('in');
        $(".test").addClass('active');
        var div = document.getElementById('accordion4');
        var elems = div.getElementsByClassName('accordion-toggle');
        for(var i=0; i<elems.length; i++)
        {

            if(elems[i].innerHTML == h1.innerHTML){
                var str = elems[i].href;
                var num = str.length - 5;
                var part = document.getElementById(str.substring(num));
                part.className = 'in';
                var elem = part.getElementsByClassName('tests');
                for(var j=0; j<elem.length; j++)
                {

                    if(elem[j].innerHTML == h4.innerHTML){

                        console.log(elem[j].innerHTML);
                        var li = elem[j].parentElement;
                        li.className = 'act';
                    }
                }
            }
        }
    });
</script>

<?php
if($this->lang == "ua")
{
    echo '<h1 id="topicId" style="display:none;">'.$this->topic['nameUa'].'</h1><h4 id="testId" style="display:none;">'.$this->test['nameUa'].'</h4>';}
else {
    echo '<h1 id="topicId" style="display:none;">'.$this->topic['name'].'</h1><h4  id="testId" style="display:none;">'.$this->test['name'].'</h4>';}
?>
<div class="question">
<?php
echo $this->errMessage;
echo '<h3>';
if($this->lang == "ua") echo 'Питання'; else echo 'Вопрос';
echo ' №'.$this->questionNumber.'</h3>';
if($this->testsArray['topicId'] == 1){
echo '<h5>';
if($this->lang == "ua") echo 'Залишилось часу'; else echo 'Осталось времени';
echo ': '.date('H:i:s',$this->time).'</h5>';}?>

    <?php
echo '<h4>'.$this->question.'</h4>';
echo $this->capture; ?>

<?php if (($this->type == 0)&&(!empty($this->answer['0']))) {?>
<table class="table table-bordered">
    <tr><td><span class="test-question">А </span> <?php echo $this->answer['0'];?> </td></tr>
    <tr><td><span class="test-question"> Б </span> <?php echo $this->answer['1'];?> </td></tr>
    <tr><td><span class="test-question"> В </span> <?php echo $this->answer['2'];?> </td></tr>
    <tr><td><span class="test-question"> Г </span> <?php echo $this->answer['3'];?> </td></tr>
</table>
<?php } ?>


<?php if ($this->type == 2) {?>
 <table class="table table-bordered">
     <tr>
         <td><span class="test-question">1 </span> <?php echo $this->answer['1'];?></td>
         <td><span class="test-question">A </span> <?php echo $this->answer['A'];?></td>
     </tr>
     <tr>
         <td><span class="test-question">2 </span> <?php echo $this->answer['2'];?></td>
         <td><span class="test-question">Б </span> <?php echo $this->answer['B'];?></td>
     </tr>
     <tr>
         <td><span class="test-question">3 </span> <?php echo $this->answer['3'];?></td>
         <td><span class="test-question">В </span> <?php echo $this->answer['C'];?></td>
     </tr>
     <tr>
         <td><span class="test-question">4 </span> <?php echo $this->answer['4'];?></td>
         <td><span class="test-question">Г </span> <?php echo $this->answer['D'];?></td>
     </tr>
     <tr>
         <td></td>
         <td><span class="test-question">Д</span> <?php echo $this->answer['E'];?></td>
     </tr>
     </table>
<?php } ?>

<?php if ($this->type == 3) {?>
    <table class="table table-bordered">

        <tr><td><span class="test-question"> 1 </span> <?php echo $this->answer['1'];?> </td></tr>
        <tr><td><span class="test-question"> 2 </span> <?php echo $this->answer['2'];?> </td></tr>
        <tr><td><span class="test-question"> 3 </span> <?php echo $this->answer['3'];?> </td></tr>
        <tr><td><span class="test-question"> 4 </span> <?php echo $this->answer['4'];?> </td></tr>
        <tr><td><span class="test-question"> 5 </span> <?php echo $this->answer['5'];?> </td></tr>
        <tr><td><span class="test-question"> 6 </span> <?php echo $this->answer['6'];?> </td></tr>
    </table>
<?php } ?>

<?php echo $this->form; ?>
<a href="/test/result/testId/<?php echo $this->testId;?>" class="btn">Завершить тест</a>


</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#testOne label').click(function(){
            $('#testOne label').css('background-position','0px -0px');
            $('#testOne label').find('input:checked').parent('#testOne label').css('background-position','0px -54px');
        });
        $('#testOne label').hover(function(){
            $('#testOne label').css('background-position','0px 0px');
            $(this).css('background-position','0px -18px');
            $('#testOne label').find('input:checked').parent('#testOne label').css('background-position','0px -72px');
            $(this).find('input:checked').parent('#testOne label').css('background-position','0px -90px');
        });
        $('#testOne label').mouseout(function(){
            $(this).find('input:checked').parent('#testOne label').css('background-position','0px -72px');});
    });

</script>