<div class="settings">
    <ul class="breadcrumb">
        <li><a href="/test/construct/"><?php if($this->lang == "ua") echo 'Конструктор тестів'; else echo 'Конструктор тестов';?></a>
            <span class="divider">/</span></li>
        <li class="active"><?php if($this->lang == "ua") echo 'Вибрати складність питання'; else echo 'Выбрать сложность вопроса';?></li>
    </ul>
<?php
echo $this->form;
?>
</div>
