<?php

$this->headTitle()->setSeparator(' - ');
$this->headTitle('Moregeo');
date_default_timezone_set('Europe/Kiev');
echo $this->doctype();
?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>


    <meta charset="utf-8">
    <script>

        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-53402346-1', 'auto');
        ga('send', 'pageview');

    </script>

    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter25746824 = new Ya.Metrika({id:25746824,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/25746824" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <link href="/img/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/slick/slick.css'); ?>

    <?php
    if ( $this->layout()->ckeditor ) {
        echo $this->headScript()->appendFile( $this->baseUrl().'/ckeditor/ckeditor.js');
    }
    ?>
    <style>
        i{
            cursor: pointer;
        }
        </style>

</head>
<body>


<div class="container">
    <a href="/"><div class="header"><p></p></div></a>
<div class="navbar">
    <div class="navbar-inner">

        <ul class="nav">
            <?php echo $this->layout()->menu;?>
        </ul>
        <form style="margin: 0;margin-top: 8px;float:right;" method="post" id="languaue">
        <input type="submit" value="ua" name="lang" id="ua" src="/img/Ukraine-Flag.png">
        <input type="submit" value="ru" name="lang" id="ru" src="/img/Russia-Flag.png">
        </form>
        <p><?php echo $this->layout()->auth;?></p>
    </div>
</div>

    <div class="single-item">
        <div class="image"><a href="http://ru.osvita.ua/test/"><img src="/img/capture01.png"></a></div>
        <div class="image"><a href="http://testportal.gov.ua/"><img src="/img/capture02.png"></a></div>
        <div class="image"><img src="/img/capture01.png"></div>
        <div class="image"><img src="/img/capture02.png"></div>
    </div>


    <div class="row-fluid">
        <div class="span3">
           <?php
           echo $this->layout()->part;?>

        </div>


        <div class="span9">
            <div id="content">
                <h1><?php echo $this->escape($this->title); ?></h1>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="dropup">
        <ul class="nav">
            <?php echo $this->layout()->menu;?>
        </ul>
            </div>
        ZNO Online Copyright 2014
    </div>


    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/slick/slick.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            $('.single-item').slick({
                autoplay: true,
                fade: true,
                speed:700,
                dots: true,
                arrows: false});
        });
    </script>





</body>
</html>
