<div class="settings">

    <h3><?php if($this->lang == "ua") echo 'Групи користувачів:'; else echo 'Группы пользователей:';?></h3>
    <p><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'addgroups')); ?>">
            <?php if($this->lang == "ua") echo 'Додати групу'; else echo 'Добавить группу';?></a></p>
    <table class="table table-condensed">
        <tr>
            <th>ID</th>
            <th width="100%"><?php if($this->lang == "ua") echo 'Назва'; else echo 'Название';?></th>
            <th></th>
            <th></th>

        </tr>
        <?php
        // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
        echo $this->partialLoop('/partials/groups.phtml', $this->groups);
        ?>
    </table>

</div>