

<h2><?php if($this->lang == "ua") echo 'Управління користувачами'; else echo 'Управление пользователями';?></h2>
<div class="settings">
        <h3><?php if($this->lang == "ua") echo 'Користувачі:'; else echo 'Пользователи:';?></h3>
        <a class="/user/groups/"><?php if($this->lang == "ua") echo 'Перейти до управління групами'; else echo 'Перейти к управлению группами';?></a>
        <table class="table table-striped table-condensed" style="font-size: 11px;">
            <tr>
                <th>ID</th>
                <th>Аватар</th>
                <th><a href="/user/settings/?params=username"><i class=" icon-arrow-down"></i> <?php if($this->lang == "ua") echo 'Нік'; else echo 'Ник';?></a></th>
                <th><a href="/user/settings/?params=email"> <i class=" icon-arrow-down"></i><?php if($this->lang == "ua") echo 'Пошта'; else echo 'Почта';?></a></th>
                <th><a href="/user/settings/?params=group"> <i class=" icon-arrow-down"></i><?php if($this->lang == "ua") echo 'Група'; else echo 'Группа';?></a></th>
                <th><a href="/user/settings/?params=class"> <i class=" icon-arrow-down"></i><?php if($this->lang == "ua") echo 'Клас'; else echo 'Класс';?></a></th>
                <th>Роль</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <?php
            // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
            echo $this->partialLoop('/partials/users.phtml', $this->paginator);
            ?>
        </table>
</div>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator_control_users.phtml'); ?>