<tr>
    <td><?php echo $this->escape($this->id); ?></td>
    <td><?php
        echo '<a href="/user/group/id/'.$this->escape($this->id).'">';
        if($_COOKIE['lang'] == "ua")
            echo $this->escape($this->nameUa);
        else
            echo $this->escape($this->name); ?>

    </a></td>
    <td><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'editgroups', 'id' => $this->id)); ?>"><i class="icon-pencil"></i></a>
    </td>
    <td>
        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'deletegroups', 'id' => $this->id)); ?>"><i class="icon-trash"></i></a>
    </td>
</tr>