<tr>
    <td><?php echo $this->escape($this->name); ?></td>
    <td><?php echo $this->escape($this->userId); ?></td>
    <td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editpart', 'id' => $this->id)); ?>">Редактировать</a>
    </td>
    <td>
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'deletepart', 'id' => $this->id)); ?>">Удалить</a>
    </td>
</tr>
