<tr>
    <td><?php echo $this->escape($this->id); ?></td>
    <td><?php echo $this->escape($this->name); ?></td>
    <td><?php $array = unserialize($this->structure);
            echo '<ul>';
            foreach ($array as $quest){
                echo '<li>'.$quest['class'].' класс : '.$quest['col'].'  ';
                if ($quest['type']== 0){ echo ' Легкий уровень ';}
                if ($quest['type']== 2){ echo ' Среднего уровень';}
                if ($quest['type']== 3){ echo ' Тяжелый уровень';}
                if ($quest['type']== 4){ echo ' Задачи';}
                echo '</li>';
            }
        echo '</ul>';
        ?></td>
    <td>
        <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'deletepattern', 'id' => $this->id)); ?>">
            <i class="icon-trash"></i></a>
    </td>
</tr>
