<div class="post" style="clear: left;">
    <h2><?php echo '<a href="/index/post/id/' . $this->escape($this->id) . '">' . $this->escape($this->titleUa) . '</a>'; ?></h2>
    <small class="muted">
        <b> Дата: </b> <?php echo date('Y-m-d H:i:s', $this->escape($this->date)); ?>
        <b> Категорія: </b>
        <?php echo '<a href="/index/category/id/' . $this->escape($this->categoryId) . '">' . $this->escape($this->categoryUa) . '</a>'; ?>
        <b>
            Користува: </b> <?php echo '<a href="/user/profile/id/' . $this->escape($this->userId) . '">' . $this->escape($this->user) . '</a>'; ?>
    </small>
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->role == 'admin') { ?>
        <div class="pull-right">
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'edit', 'id' => $this->id)); ?>">

                <i class="icon-pencil"></i></a>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'delete', 'id' => $this->id)); ?>">
                <i class="icon-trash"></i></a>
        </div>
    <?php } ?>
    <div class="inner">
    <?php echo '<img src="' . $this->escape($this->icon) . '" style="padding:20px;padding-top:0;float:left;width:300px;">'; ?>
    <?php echo htmlspecialchars_decode($this->escape($this->descriptionUa)); ?>
    <hr>
        <div class="read"><?php echo '<a href="/index/post/id/' . $this->escape($this->id) . '">Читати далі...</a>'; ?>
        </div>
    </div>
</div>
