<div class="post" style="clear: left;">
    <h2><?php echo '<a href="/index/post/id/' . $this->escape($this->id) . '">' . $this->escape($this->title) . '</a>'; ?></h2>
    <small class="muted">
        <div class="date"><b> Дата: </b> <?php echo date('d.m.Y', $this->escape($this->date)); ?></div>
        <div class="category"> <b> Категория: </b>
        <?php echo '<a href="/index/category/id/' . $this->escape($this->categoryId) . '">' . $this->escape($this->category) . '</a>'; ?>
        <b> </div>
        <div class="user">  Пользователь </b> <?php echo '<a href="/user/profile/id/' . $this->escape($this->userId) . '">' . $this->escape($this->user) . '</a>'; ?>
        </div>
    </small>
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->role == 'admin') { ?>
        <div class="pull-right">
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'edit', 'id' => $this->id)); ?>">

                <i class="icon-pencil"></i></a>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'delete', 'id' => $this->id)); ?>">
                <i class="icon-trash"></i></a>
        </div>
    <?php } ?>

    <div class="inner">
    <?php echo '<img src="' . $this->escape($this->icon) . '">'; ?>
    <?php echo htmlspecialchars_decode($this->escape($this->description)); ?>
    <hr>
        <div class="read"><?php echo '<a href="/index/post/id/' . $this->escape($this->id) . '">Читать далее...</a>'; ?>
        </div>
    </div>
</div>
