<tr>
    <td><?php echo $this->escape($this->nameUa); ?></td>
    <td><?php echo $this->escape($this->topicId); ?></td>
    <td >
        <?php  if (Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->role == 'admin')  {?>

            <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'deletequestion', 'id' => $this->id)); ?>"><i class="icon-trash"></i></a>
        <?php }?>
    </td>

</tr>
