<tr>
    <td><?php echo $this->escape($this->id); ?></td>
    <td><?php echo '<a href="/user/profile/id/'
            .$this->escape($this->id)
            .'"><img src="'; if($this->photo == NULL)
                                        echo '/img/profile.png';
                                 else
                                        echo $this->photo;

        echo '" width="32" height="32"></a>'; ?></td>

    <td><?php echo $this->escape($this->username); ?></td>
    <td><?php echo $this->escape($this->email); ?></td>
    <td><?php echo $this->escape($this->group); ?></td>
    <td><?php echo $this->escape($this->role); ?></td>

    <td>
        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete', 'id' => $this->id)); ?>"><i class="icon-trash"></i></a>
    </td>
</tr>