<tr>
    <td><?php echo $this->escape($this->id); ?></td>
    <td><?php echo $this->escape($this->username); ?></td>
    <td><?php echo $this->escape($this->email); ?></td>
    <td><?php echo $this->escape($this->role); ?></td>
    <td>
        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'deleteuser', 'id' => $this->id, 'groupId' =>  $_SESSION['group'])); ?>"><i class="icon-trash"></i></a>
    </td>
</tr>