<tr>
    <td><?php echo $this->escape($this->id); ?></td>
    <td><?php echo $this->escape($this->username); ?></td>
    <td><?php echo $this->escape($this->email); ?></td>
    <td><?php echo $this->escape($this->role); ?></td>
    <td>
        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'adduser', 'id' => $this->id, 'groupId' =>  $_SESSION['group'])); ?>">
            <i class="icon-plus"></i></a>
    </td>
</tr>